# COMMON args
method: ours 
model_name: FcNet4
training_epoch: 80 # 80
batch_size: 50
lr_prior: 0.001

#------------------------------------------------------------------------------------
#DATASET related
dataset: toxic
sens_attrs: race # toxic race 5, religion 5, gender 4, wilds 6, mix 12 
N_subtask: 5
acc_bar: 0.4 # toxic
lower_rate: 3 # amazon
upper_rate: 4 # amazon


#------------------------------------------------------------------------------------
# METHOD Specific
# ours 
lr_post: 0.4  # 0.2
weight: 0.4 # 0.6
max_inner: 10
max_outer: 5
divergence_type: W_Sqr  # W_Sqr KL
kappa_prior: 0.01
kappa_post: 0.001

log_var_init_mean: 0.01 #-0.1
log_var_init_var: 0.01 #0.1
eps_std: 0.08
n_MC: 5

#------------------------------------------------------------------------------------
# CUSTOMER
seed: 0
train_inf_step: 2
use_wandb: False
wandb_username: YOURWANDBNAME
exp_name: toxic_race_example

#------------------------------------------------------------------------------------
#POST
# acc
acc_bin: 0.5
# suf gap
params:
    n_bins: 5 
    interpolate_kind: 'linear'  











